export class CreateOrderDto {
  userId: number;
  status: string;
  orderDate?: Date; // Optional, as this may be automatically generated by Prisma
  items: {
    productId: number;
    quantity: number;
  }[];
}
